[package]
name = "aoc24"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
fxhash = "0.2.1"
itertools = "0.13.0"
memchr = "2.7.4"